const record = {
  title:
    "Hutong Bilingual Toastmasters Club - 532nd English Meeting Ah-Counter Report",
  speakers: [
    {
      speaker: "TT1",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "more", count: 1 },
        { word: "they", count: 1 },
        { word: "er", count: 3 },
        { word: "to", count: 2 },
        { word: "when", count: 1 },
      ],
    },
    {
      speaker: "TT2",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "er", count: 5 },
        { word: "so", count: 2 },
        { word: "um", count: 3 },
        { word: "and", count: 2 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "TT3",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "well", count: 1 },
        { word: "like", count: 3 },
        { word: "er", count: 3 },
        { word: "yeah", count: 1 },
        { word: "so", count: 1 },
      ],
    },
    {
      speaker: "TT4",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "so", count: 2 },
        { word: "er", count: 4 },
        { word: "um", count: 3 },
        { word: "between", count: 1 },
        { word: "we", count: 3 },
      ],
    },
    {
      speaker: "TT5",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "er", count: 5 },
        { word: "um", count: 2 },
        { word: "er", count: 0 },
        { word: "and", count: 0 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "TT6",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "er", count: 3 },
        { word: "um", count: 1 },
        { word: "yeah", count: 1 },
        { word: "in", count: 1 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "TT7",
      role: "Table Topic Speaker",
      fillerWords: [
        { word: "the", count: 3 },
        { word: "er", count: 1 },
        { word: "yeah", count: 2 },
        { word: "yes", count: 1 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "TTM-Cathy",
      role: "Table Topic Master",
      fillerWords: [
        { word: "er", count: 8 },
        { word: "in", count: 1 },
        { word: "when", count: 1 },
        { word: "to", count: 1 },
        { word: "I", count: 1 },
        { word: "um", count: 1 },
      ],
    },
    {
      speaker: "TTE-Celia",
      role: "Table Topic Evaluator",
      fillerWords: [
        { word: "er", count: 4 },
        { word: "in", count: 1 },
        { word: "ok", count: 2 },
        { word: "um", count: 1 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "Prepared1-Nebula",
      role: "Prepared Speaker",
      fillerWords: [
        { word: "um", count: 3 },
        { word: "er", count: 4 },
        { word: "to", count: 1 },
        { word: "and", count: 1 },
        { word: "why", count: 1 },
        { word: "you know", count: 1 },
      ],
    },
    {
      speaker: "Prepared2-Elsa Li",
      role: "Prepared Speaker",
      fillerWords: [
        { word: "er", count: 1 },
        { word: "and", count: 1 },
        { word: "er", count: 0 },
        { word: "and", count: 0 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "Prepared3-Edward",
      role: "Prepared Speaker",
      fillerWords: [
        { word: "year", count: 3 },
        { word: "and", count: 2 },
        { word: "the", count: 3 },
        { word: "um", count: 1 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "Evaluator1-Jessie",
      role: "Evaluator",
      fillerWords: [
        { word: "er", count: 3 },
        { word: "and", count: 2 },
        { word: "ok", count: 1 },
        { word: "and", count: 0 },
        { word: "you know", count: 1 },
      ],
    },
    {
      speaker: "Evaluator2-Lily Zhou",
      role: "Evaluator",
      fillerWords: [
        { word: "er", count: 2 },
        { word: "um", count: 1 },
        { word: "er", count: 0 },
        { word: "and", count: 0 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "Evaluator3-Cathy",
      role: "Evaluator",
      fillerWords: [
        { word: "er", count: 7 },
        { word: "but", count: 1 },
        { word: "to", count: 2 },
        { word: "um", count: 2 },
        { word: "you know", count: 1 },
      ],
    },
    {
      speaker: "GE-Yanny",
      role: "General Evaluator",
      fillerWords: [
        { word: "um", count: 2 },
        { word: "er", count: 7 },
        { word: "to", count: 1 },
        { word: "but", count: 1 },
        { word: "you know", count: 0 },
      ],
    },
    {
      speaker: "TMoE-Cathy",
      role: "TMoE",
      fillerWords: [
        { word: "so", count: 3 },
        { word: "then", count: 1 },
        { word: "and", count: 2 },
        { word: "um", count: 1 },
        { word: "to", count: 1 },
        { word: "ah", count: 1 },
        { word: "you know", count: 7 },
      ],
    },
  ],
};
